use rand::Rng;
use serde::{Deserialize, Serialize};

/// the Word struct represent a struct of words to be malformed
#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct Word {
    /// the original word
    word: String,
    /// meaning of the word
    meaning: String,
}

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct Jumble {
    /// the original word
    pub word: String,
    /// meaning of the word
    pub meaning: String,
    /// the scrabbled word
    pub scrabble: String,
}

impl Word {
    pub fn from(word: &str, meaning: &str) -> Self {
        Self {
            word: word.to_string(),
            meaning: meaning.to_string(),
        }
    }
}

// the library contains all words to be Wordd, the meanings and the Wordd ones
#[derive(Debug, Serialize, Deserialize)]

pub struct Library {
    /// all the available words
    pub words: Vec<Word>,
    /// the legth of the available words
    pub length: usize,
}

impl Library {
    // pick a word from the library and jumble it
    pub fn new_jumble() -> Jumble {
        let library = Library {
            words: Self::word_list(),
            length: Self::word_list().len(),
        };

        // generate an index in the range of the randoom words
        let mut rng = rand::thread_rng();
        let word_index = rng.gen_range(0..=library.length);
        let fetched_word = &library.words[word_index];
        // scrabble the word
        let mut scrabble_word = |word: String| -> String {
            let mut new_word = String::new();
            let mut char_array: Vec<usize> = Vec::new();
            while new_word.len() != word.len() {
                // create a random index of the string
                let char_index = rng.gen_range(0..word.len());
                if !char_array.contains(&char_index) {
                    char_array.push(char_index);
                    // create the new word
                    // new_word.push(word.as_bytes()[char_index]);
                    new_word.push(word.as_bytes()[char_index] as char);
                }
            }
            new_word
        };
        Jumble {
            word: fetched_word.clone().word,
            meaning: fetched_word.clone().meaning,
            scrabble: scrabble_word(fetched_word.clone().word),
        }
    }

    fn word_list() -> Vec<Word> {
        vec![
    Word::from( "about", "on the subject of; concerning"),
    Word::from( "above", "at a higher level or layer"),
    Word::from( "abroad", "in or to a foreign country"),
    Word::from( "absorb", "take in or soak up"),
    Word::from( "abuse", "use something to bad effect or for a bad purpose"),
    Word::from( "accept", "consent to receive or undertake"),
    Word::from( "access", "the means of approaching or entering a place"),
    Word::from( "accuse", "charge someone with an offense or crime"),
    Word::from( "across", "from one side to the other"),
    Word::from( "action", "the process of doing something"),
    Word::from( "active", "engaging or ready to engage in physically energetic pursuits"),
    Word::from( "actor", "a person whose profession is acting on stage, in movies, or on television"),
    Word::from( "actual", "existing in fact; real"),
    Word::from( "adapt", "make suitable for a new use or purpose"),
    Word::from( "adjust", "alter or move something slightly to achieve the desired fit"),
    Word::from( "admire", "regard with respect or warm approval"),
    Word::from( "admit", "confess to be true or to be the case"),
    Word::from( "adopt", "legally take another's child and bring it up as one's own"),
    Word::from( "adult", "a person who is fully grown or developed"),
    Word::from( "advice", "guidance or recommendations offered with regard to prudent action"),
    Word::from( "advise", "offer suggestions about the best course of action"),
    Word::from( "affair", "an event or sequence of events of a specified kind"),
    Word::from( "affect", "have an effect on; make a difference to"),
    Word::from( "afford", "have enough money to pay for"),
    Word::from( "afraid", "feeling fear or anxiety"),
    Word::from( "after", "in the time following an event or another period of time"),
    Word::from( "again", "another time; once more"),
    Word::from( "agency", "a business or organization providing a particular service"),
    Word::from( "agenda", "a list of items to be discussed at a meeting"),
    Word::from( "agent", "a person who acts on behalf of another"),
    Word::from( "agree", "have the same opinion about something"),
    Word::from( "ahead", "further forward in space; in the line of one's forward motion"),
    Word::from( "album", "a collection of recordings issued as a single item on CD, record, or another medium"),
    Word::from( "alive", "living, not dead"),
    Word::from( "allow", "give permission to do something"),
    Word::from( "almost", "not quite; very nearly"),
    Word::from( "alone", "having no one else present"),
    Word::from( "along", "moving in a constant direction on a path"),
    Word::from( "alter", "change or cause to change in character or composition"),
    Word::from( "always", "at all times; on all occasions"),
    Word::from( "among", "surrounded by; in the company of"),
    Word::from( "amount", "a quantity of something"),
    Word::from( "anger", "a strong feeling of annoyance, displeasure, or hostility"),
    Word::from( "angle", "the space between two intersecting lines or surfaces"),
    Word::from( "angry", "feeling or showing strong annoyance or displeasure"),
    Word::from( "animal", "a living organism that feeds on organic matter"),
    Word::from( "annual", "occurring once every year"),
    Word::from( "answer", "a response to a question"),
    Word::from( "anyone", "any person or people"),
    Word::from( "anyway", "used to confirm or support a point or idea"),
    Word::from( "apart", "separated by a distance"),
    Word::from( "appeal", "make a serious or urgent request"),
    Word::from( "appear", "come into sight; become visible or noticeable"),
    Word::from( "apple", "the round fruit of a tree of the rose family"),
    Word::from( "apply", "make a formal application or request"),
    Word::from( "argue", "give reasons or cite evidence in support of an idea"),
    Word::from( "arise", "emerge; become apparent"),
    Word::from( "armed", "equipped with or carrying a weapon"),
    Word::from( "around", "located or situated on every side"),
    Word::from( "arrest", "seize someone by legal authority and take into custody"),
    Word::from( "arrive", "reach a place at the end of a journey"),
    Word::from( "artist", "a person who creates paintings or drawings"),
    Word::from( "Asian", "relating to Asia or its people, customs, or languages"),
    Word::from( "aside", "to one side; out of the way"),
    Word::from( "asleep", "in a state of sleep"),
    Word::from( "aspect", "a particular part or feature of something"),
    Word::from( "assert", "state a fact or belief confidently and forcefully"),
    Word::from( "assess", "evaluate or estimate the nature, ability, or quality of"),
    Word::from( "asset", "a useful or valuable thing, person, or quality"),
    Word::from( "assign", "allocate a job or duty"),
    Word::from( "assist", "help someone, typically by doing a share of the work"),
    Word::from( "assume", "suppose to be the case, without proof"),
    Word::from( "assure", "tell someone something positively to dispel any doubts"),
    Word::from( "attach", "fasten; join"),
    Word::from( "attack", "take aggressive action against"),
    Word::from( "attend", "be present at an event, meeting, or function"),
    Word::from( "author", "a writer of a book, article, or report"),
    Word::from( "avoid", "keep away from or stop oneself from doing something"),
    Word::from( "award", "give or order the giving of something as an official payment, compensation, or prize"),
    Word::from( "aware", "having knowledge or perception of a situation or fact"),
    Word::from( "awful", "very bad or unpleasant"),
    Word::from( "badly", "in an unsatisfactory, inadequate, or unsuccessful way"),
    Word::from( "barely", "only just; almost not"),
    Word::from( "barrel", "a cylindrical container bulging out in the middle"),
    Word::from( "basic", "forming an essential foundation or starting point"),
    Word::from( "basis", "the underlying support or foundation for an idea, argument, or process"),
    Word::from( "basket", "a container used to hold or carry things"),
    Word::from( "battle", "a sustained fight between large, organized armed forces"),
    Word::from( "beach", "a pebbly or sandy shore"),
    Word::from( "beauty", "a combination of qualities that pleases the aesthetic senses"),
    Word::from( "become", "begin to be"),
    Word::from( "before", "during the period of time preceding a particular event or time"),
    Word::from( "begin", "start; perform or undergo the first part of an action or activity"),
    Word::from( "behind", "at or to the far side of (something), typically so as to be hidden by it"),
    Word::from( "being", "existence"),
    Word::from( "belief", "an acceptance that something exists or is true, especially one without proof"),
    Word::from( "belong", "be the property of"),
    Word::from( "below", "at a lower level or layer"),
    Word::from( "bench", "a long seat for several people, typically made of wood or stone"),
    Word::from( "beside", "at the side of; next to"),
    Word::from( "better", "more desirable, satisfactory, or effective"),
    Word::from( "beyond", "at or to the further side of"),
    Word::from( "Bible", "the Christian scriptures, consisting of the Old and New Testaments"),
    Word::from( "birth", "the emergence of a baby or other young from the body of its mother"),
    Word::from( "black", "of the very darkest color owing to the absence of or complete absorption of light"),
    Word::from( "blade", "the flat cutting edge of a knife, saw, or other tool or weapon"),
    Word::from( "blame", "assign responsibility for a fault or wrong"),
    Word::from( "blind", "unable to see"),
    Word::from( "block", "a large solid piece of hard material, especially rock, stone, or wood"),
    Word::from( "blood", "the red liquid that circulates in the arteries and veins of humans and other vertebrate animals"),
    Word::from( "board", "a long, thin, flat piece of wood or other hard material"),
    Word::from( "border", "a line separating two political or geographical areas, especially countries"),
    Word::from( "borrow", "take and use something belonging to someone else with the intention of returning it"),
    Word::from( "bother", "take the trouble to do something"),
    Word::from( "bottle", "a container, typically made of glass or plastic and with a narrow neck, used for storing drinks or other liquids"),
    Word::from( "bottom", "the lowest point or part of something"),
    Word::from( "brain", "an organ of soft nervous tissue contained in the skull of vertebrates, functioning as the coordinating center of sensation and intellectual and nervous activity"),
    Word::from( "branch", "a part of a tree that grows out from the trunk or from a bough"),
    Word::from( "brand", "a type of product manufactured by a particular company under a particular name"),
    Word::from("bread", "food made of flour, water, and yeast mixed together and baked"),
    Word::from( "break", "separate into pieces as a result of a blow, shock, or strain"),
    Word::from( "breast", "either of the two soft, protruding organs on the upper front of a woman's body that secrete milk after pregnancy"),
    Word::from( "breath", "the air taken into or expelled from the lungs"),
    Word::from( "brick", "a small rectangular block typically made of fired or sun-dried clay, used in building"),
    Word::from( "bridge", "a structure carrying a road, path, railroad, or canal across a river, ravine, road, railroad, or other obstacle"),
    Word::from( "brief", "of short duration"),
    Word::from( "bright", "giving out or reflecting a lot of light; shining"),
    Word::from("bring", "take or go with to a place"),
    Word::from( "broad", "having an ample distance from side to side"),
    Word::from( "broken", "having been fractured or damaged and no longer in one piece or in working order"),
    Word::from( "brown", "of a color produced by mixing red, yellow, and blue, as of dark wood or rich soil"),
    Word::from( "brush", "an implement with a handle, consisting of bristles, hair, or wire set into a block, used for cleaning, smoothing, or painting"),
    Word::from( "budget", "an estimate of income and expenditure for a set period of time"),
    Word::from( "build", "construct by putting parts or material together"),
    Word::from( "bullet", "a projectile for firing from a rifle, revolver, or other small firearm"),
    Word::from( "bunch", "a number of things, typically of the same kind, growing or fastened together"),
    Word::from( "burden", "a load, typically a heavy one"),
    Word::from( "butter", "a pale yellow edible fatty substance made by churning cream and used as a spread or in cooking"),
    Word::from( "button", "a small disc or knob sewn onto a garment, either to fasten it by being pushed through a buttonhole or for decoration"),
    Word::from( "buyer", "a person who makes a purchase"),
    Word::from( "cabin", "a small shelter or house, made of wood and situated in a wild or remote area"),
    Word::from( "cable", "a thick rope of wire or nonmetallic fiber, typically used for construction, mooring ships, and towing vehicles"),
    Word::from( "camera", "a device for recording visual images in the form of photographs, film, or video signals"),
    Word::from( "campus", "the grounds and buildings of a university or college"),
    Word::from( "cancer", "a disease caused by an uncontrolled division of abnormal cells in a part of the body"),
    Word::from( "carbon", "the chemical element of atomic number 6, a nonmetal that has two main forms (diamond and graphite), and that also occurs in impure form in charcoal, soot, and coal"),
    Word::from( "career", "an occupation undertaken for a significant period of a person's life and with opportunities for progress"),
    Word::from( "carry", "support and move someone or something from one place to another"),
    Word::from( "catch", "intercept and hold something that has been thrown, propelled, or dropped"),
    Word::from( "cause", "a person or thing that gives rise to an action, phenomenon, or condition"),
    Word::from( "center", "the middle point of a circle or sphere, equidistant from every point on the circumference or surface"),
    Word::from( "chain", "a series of linked metal rings used for fastening or securing something, or for pulling loads"),
    Word::from( "chair", "a separate seat for one person, typically with a back and four legs"),
    Word::from( "chance", "a possibility of something happening"),
    Word::from( "change", "make or become different"),
    Word::from( "charge", "demand an amount as a price from someone for a service rendered or goods supplied"),
    Word::from( "chart", "a sheet of information in the form of a table, graph, or diagram"),
    Word::from( "chase", "pursue in order to catch or catch up with"),
    Word::from( "cheap", "low in price, especially in relation to similar items or services"),
    Word::from( "check", "examine something in order to determine its accuracy, quality, or condition"),
    Word::from( "cheek", "either side of the face below the eye"),
    Word::from( "cheese", "a food made from the pressed curds of milk"),
Word::from( "chest", "A box or container for storage"),
  Word::from( "chief", "The leader or head of a group"),
  Word::from( "child", "A young human being"),
  Word::from( "choice", "An act of selecting or making a decision"),
  Word::from( "choose", "To pick out or select"),
  Word::from( "church", "A building used for public worship"),
  Word::from( "circle", "A round shape with all points equidistant from the center"),
  Word::from( "civil", "Relating to ordinary citizens and their concerns"),
  Word::from( "claim", "To assert something as a fact"),
  Word::from( "class", "A group of students who meet regularly to be taught a subject"),
  Word::from( "clean", "Free from dirt, marks, or stains"),
  Word::from( "clear", "Easy to perceive, understand, or interpret"),
  Word::from( "client", "A person or organization using the services of a professional"),
  Word::from( "climb", "To go up or ascend"),
  Word::from( "clinic", "A place where patients receive medical treatment"),
  Word::from( "clock", "A device for measuring and showing time"),
  Word::from( "close", "To move so as to cover an opening"),
  Word::from( "closer", "More near in space or time"),
  Word::from( "cloud", "A visible mass of condensed water vapor in the sky"),
  Word::from( "coach", "A person who trains and instructs"),
  Word::from( "coast", "The part of the land near the sea"),
  Word::from( "coffee", "A beverage made from roasted coffee beans"),
  Word::from( "color", "The property possessed by an object of producing different sensations on the eye"),
  Word::from( "column", "An upright pillar or post"),
  Word::from( "comedy", "A genre of film, television, or literature that is humorous"),
  Word::from( "commit", "To pledge or bind to a certain course or policy"),
  Word::from( "common", "Occurring, found, or done often"),
  Word::from( "cookie", "A sweet baked food that is usually small, flat, and round"),
  Word::from( "corner", "The point where two lines or surfaces meet"),
  Word::from( "cotton", "A soft white fibrous substance that surrounds the seeds of a tropical plant"),
  Word::from( "couch", "A piece of furniture for seating multiple people"),
  Word::from( "could", "Used to indicate possibility"),
  Word::from( "count", "To determine the total number of items"),
  Word::from( "county", "A territorial division of a country"),
  Word::from( "couple", "Two people or things of the same sort considered together"),
  Word::from( "course", "A direction or route taken"),
  Word::from( "court", "A place where legal matters are decided"),
  Word::from( "cousin", "A child of one's uncle or aunt"),
  Word::from( "cover", "To place something over or upon"),
  Word::from( "crack", "A line on the surface of something along which it has split"),
  Word::from( "craft", "An activity involving skill in making things by hand"),
  Word::from( "crash", "To collide violently"),
  Word::from( "crazy", "Mad or insane"),
  Word::from( "cream", "A thick liquid or semi-solid food, typically rich in fat"),
  Word::from( "create", "To bring something into existence"),
  Word::from( "credit", "The ability of a customer to obtain goods or services before payment"),
  Word::from( "crime", "An illegal act"),
  Word::from( "crisis", "A time of intense difficulty or danger"),
  Word::from( "critic", "A person who judges the merits of literary, artistic, or musical works"),
  Word::from( "cross", "A mark, object, or figure formed by two intersecting lines"),
  Word::from( "crowd", "A large number of people gathered together"),
  Word::from( "custom", "A traditional practice or usual way of doing something"),
  Word::from( "cycle", "A series of events that are regularly repeated in the same order"),
  Word::from( "daily", "Done, produced, or occurring every day"),
  Word::from( "damage", "Physical harm that impairs the value, usefulness, or normal function of something"),
  Word::from( "dance", "Move rhythmically to music"),
  Word::from( "danger", "The possibility of suffering harm or injury"),
  Word::from( "dealer", "A person who buys and sells goods"),
  Word::from( "death", "The end of the life of a person or organism"),
  Word::from( "debate", "A formal discussion on a particular topic"),
  Word::from( "decade", "A period of ten years"),
  Word::from( "decide", "To make a choice from a number of alternatives"),
  Word::from( "deeply", "Extending far down from the top or surface"),
  Word::from( "defeat", "To win a victory over someone in a battle or contest"),
  Word::from( "defend", "To protect from harm or danger"),
  Word::from( "define", "To state or describe exactly the nature, scope, or meaning of something"),
  Word::from( "degree", "A unit of measurement for angles or temperature"),
  Word::from( "delay", "To postpone or put off to a later time"),
  Word::from( "demand", "An insistent and peremptory request"),
  Word::from( "depend", "To be controlled or determined by"),
  Word::from( "depict", "To show or represent by a drawing, painting, or other art form"),
  Word::from( "depth", "The distance from the top or surface to the bottom of something"),
  Word::from( "deputy", "A person who is appointed to undertake the duties of a superior in the superior's absence"),
  Word::from( "derive", "To obtain something from a specified source"),
  Word::from( "desert", "A barren area of landscape where little precipitation occurs"),
  Word::from( "design", "A plan or drawing produced to show the look and function of an object before it is built"),
  Word::from( "desire", "A strong feeling of wanting to have something"),
  Word::from( "detail", "An individual feature, fact, or item"),
  Word::from( "detect", "To discover or identify the presence of something"),
  Word::from( "device", "A thing made or adapted for a particular purpose"),
  Word::from( "devote", "To give all or a large part of one's time or resources to something"),
  Word::from( "differ", "To be unlike or distinct in nature"),
  Word::from( "dining", "The activity of eating a meal"),
  Word::from( "dinner", "The main meal of the day, usually in the evening"),
  Word::from( "direct", "To manage or guide by advice or instruction"),
  Word::from( "dirty", "Covered or marked with an unclean substance"),
  Word::from( "divide", "To separate into parts"),
  Word::from( "doctor", "A person qualified to practice medicine"),
  Word::from( "double", "Consisting of two equal, identical, or similar parts"),
  Word::from( "doubt", "A feeling of uncertainty or lack of conviction"),
  Word::from( "dozen", "A group or set of twelve"),
  Word::from( "draft", "A preliminary version of a piece of writing"),
  Word::from( "drama", "A play for theater, radio, or television"),
  Word::from( "dream", "A series of thoughts, images, and sensations occurring in a person's mind during sleep"),
  Word::from( "dress", "To put on one's clothes"),
  Word::from( "drink", "To take a liquid into the mouth and swallow"),

  Word::from( "drive", "to operate and control a vehicle"),
  Word::from( "driver", "a person who operates a vehicle"),
  Word::from( "during", "throughout the entire time of"),
  Word::from( "eager", "very enthusiastic and keen to do something"),
  Word::from( "early", "happening or done before the usual or expected time"),
  Word::from( "earth", "the planet on which we live"),
  Word::from( "easily", "without difficulty or effort"),
  Word::from( "editor", "a person who prepares written material for publication"),
  Word::from( "effect", "a change that is a result of an action or other cause"),
  Word::from( "effort", "a vigorous or determined attempt"),
  Word::from( "eight", "the number after seven and before nine"),
  Word::from( "either", "used to indicate a choice between two alternatives"),
  Word::from( "elect", "to choose someone to hold public office or some other position by voting"),
  Word::from( "elite", "a group of people considered to be the best in a particular society or category"),
  Word::from( "e-mail", "a system for sending messages from one computer to another"),
  Word::from( "emerge", "to come into view or become apparent"),
  Word::from( "employ", "to give work to someone and pay them for it"),
  Word::from( "empty", "containing nothing; not filled or occupied"),
  Word::from( "enable", "to give someone the means or ability to do something"),
  Word::from( "enemy", "a person who is actively opposed or hostile to someone or something"),
  Word::from( "energy", "the strength and vitality required for sustained physical or mental activity"),
  Word::from( "engage", "to participate or become involved in"),
  Word::from( "engine", "a machine with moving parts that converts power into motion"),
  Word::from( "enjoy", "to take delight or pleasure in an activity or occasion"),
  Word::from( "enough", "as much or as many as required"),
  Word::from( "ensure", "to make certain that something will occur or be the case"),
  Word::from( "enter", "to go or come into a place"),
  Word::from( "entire", "with no part left out; whole"),
  Word::from( "entry", "an act of going or coming in"),
  Word::from( "equal", "being the same in quantity, size, degree, or value"),
  Word::from( "error", "a mistake"),
  Word::from( "escape", "to break free from confinement or control"),
  Word::from( "essay", "a short piece of writing on a particular subject"),
  Word::from( "estate", "an area or amount of land or property"),
  Word::from( "ethics", "moral principles that govern a person's behavior"),
  Word::from( "ethnic", "relating to a population subgroup with a common national or cultural tradition"),
  Word::from( "event", "a thing that happens, especially one of importance"),
  Word::from( "every", "used to refer to all the individual members of a set without exception"),
  Word::from( "evolve", "to develop gradually"),
  Word::from( "exact", "not approximated in any way; precise"),
  Word::from( "exceed", "to be greater in number or size than"),
  Word::from( "except", "not including; other than"),
  Word::from( "exist", "to have objective reality or being"),
  Word::from( "expand", "to increase in size, number, or importance"),
  Word::from( "expect", "to regard something as likely to happen"),
  Word::from( "expert", "a person with comprehensive and authoritative knowledge of a skill or subject"),
  Word::from( "expose", "to make something visible by uncovering it"),
  Word::from( "extend", "to cause something to cover a larger area; to make longer"),
  Word::from( "extent", "the area covered by something"),
  Word::from( "extra", "added to an existing or usual amount or number"),
  Word::from( "fabric", "cloth, typically produced by weaving or knitting textile fibers"),
  Word::from( "factor", "a circumstance, fact, or influence that contributes to a result"),
  Word::from( "fairly", "with justice; justly"),
  Word::from( "faith", "complete trust or confidence in someone or something"),
  Word::from( "false", "not according with truth or fact; incorrect"),
  Word::from( "family", "a group consisting of parents and children living together in a household"),
  Word::from( "famous", "known about by many people"),
  Word::from( "farmer", "a person who owns or manages a farm"),
  Word::from( "father", "a man in relation to his child or children"),
  Word::from( "fault", "an unattractive or unsatisfactory feature, especially in a piece of work or in a person's character"),
  Word::from( "favor", "an act of kindness beyond what is due or usual"),
  Word::from( "fellow", "a person in the same position, involved in the same activity, or otherwise associated with another"),
  Word::from( "female", "of or denoting the sex that can bear offspring or produce eggs"),
  Word::from( "fence", "a barrier, railing, or other upright structure enclosing an area of ground to mark a boundary, control access, or prevent escape"),
  Word::from( "fewer", "a smaller number of"),
  Word::from( "fiber", "a thread or filament from which a vegetable tissue, mineral substance, or textile is formed"),
  Word::from( "field", "an area of open land, especially one planted with crops or pasture"),
  Word::from( "fifth", "constituting number five in a sequence; 5th"),
  Word::from( "fifty", "the number equivalent to the product of five and ten; 50"),
  Word::from( "fight", "a violent confrontation or struggle"),
  Word::from( "figure", "a number, especially one which forms part of official statistics or relates to the financial performance of a company"),
  Word::from( "final", "coming at the end of a series"),
  Word::from( "finger", "each of the four slender jointed parts attached to either hand"),
  Word::from( "finish", "bring (a task or activity) to an end; complete"),
  Word::from( "first", "coming before all others in time or order"),
  Word::from( "flame", "a hot glowing body of ignited gas that is generated by something on fire"),
  Word::from( "flavor", "the distinctive taste of a food or drink"),
  Word::from( "flesh", "the soft substance consisting of muscle and fat that is found between the skin and bones of an animal or a human"),
  Word::from( "flight", "the action or process of flying through the air"),
  Word::from( "float", "to rest or move on or near the surface of a liquid without sinking"),
  Word::from( "floor", "the lower surface of a room, on which one may walk"),
  Word::from( "flower", "the seed-bearing part of a plant, consisting of reproductive organs that are typically surrounded by a brightly colored corolla"),
  Word::from( "focus", "the center of interest or activity"),
  Word::from( "follow", "to go or come after a person or thing proceeding ahead; move or travel behind"),
  Word::from( "force", "strength or energy as an attribute of physical action or movement"),
  Word::from( "forest", "a large area covered chiefly with trees and undergrowth"),
  Word::from( "forget", "fail to remember"),
  Word::from( "formal", "done in accordance with convention or etiquette; suitable for or constituting an official or important situation or occasion"),
  Word::from( "former", "having previously filled a particular role or been a particular thing"),
  Word::from( "forth", "out from a starting point and forward or into view"),
  Word::from( "found", "having been discovered by chance or unexpectedly"),
  Word::from( "fourth", "constituting number four in a sequence"),
    Word::from( "frame",  "a structure that provides support or shape"),
    Word::from( "freeze",  "to turn into ice or become solid due to cold"),
    Word::from( "French",  "relating to France or its people or language"),
    Word::from( "fresh",  "recently made or obtained; not stale or spoiled"),
    Word::from( "friend",  "a person with whom one has a bond of mutual affection"),
    Word::from( "front",  "the foremost part or surface of something"),
    Word::from( "fruit",  "the sweet and fleshy product of a tree or plant"),
    Word::from( "fully",  "completely or entirely"),
    Word::from( "funny",  "causing laughter or amusement"),
    Word::from( "future",  "the time yet to come"),
    Word::from( "galaxy",  "a system of millions or billions of stars, together with gas and dust"),
    Word::from( "garage",  "a building for housing a motor vehicle or vehicles"),
    Word::from( "garden",  "a piece of ground, often near a house, used for growing flowers, fruit, or vegetables"),
    Word::from( "garlic",  "a strong-smelling pungent-tasting bulb, used as a flavoring in cooking and in herbal medicine"),
    Word::from( "gather",  "to collect or bring together"),
    Word::from( "gender",  "the state of being male or female"),
    Word::from( "gently",  "in a kind and careful way as not to hurt or upset anyone or anything"),
    Word::from( "German",  "relating to Germany, its people, or their language"),
    Word::from( "ghost",  "an apparition of a dead person that is believed to appear or become manifest to the living"),
    Word::from( "giant",  "an imaginary or mythical being of human form but superhuman size"),
    Word::from( "gifted",  "having exceptional talent or natural ability"),
    Word::from( "given",  "specified or stated"),
    Word::from( "glance",  "to take a brief or hurried look"),
    Word::from( "glass",  "a hard, brittle substance, typically transparent or translucent, made by fusing sand with soda and lime"),
    Word::from( "global",  "relating to the whole world; worldwide"),
    Word::from( "glove",  "a covering for the hand worn for protection against cold or dirt and typically having separate parts for each finger and the thumb"),
    Word::from( "golden",  "colored or shining like gold"),
    Word::from( "grade",  "a particular level of rank, quality, proficiency, or value"),
    Word::from( "grain",  "wheat or any other cultivated cereal crop used as food"),
    Word::from( "grand",  "magnificent and imposing in appearance, size, or style"),
    Word::from( "grant",  "agree to give or allow (something requested) to"),
    Word::from( "grass",  "vegetation consisting of typically short plants with long narrow leaves, growing wild or cultivated on lawns and pasture"),
    Word::from( "grave",  "a place of burial for a dead body, typically a hole dug in the ground and marked by a stone or mound"),
    Word::from( "great",  "of an extent, amount, or intensity considerably above the normal or average"),
    Word::from( "green",  "of the color between blue and yellow in the spectrum; colored like grass or emeralds"),
    Word::from( "ground",  "the solid surface of the earth"),
    Word::from( "group",  "a number of people or things that are located, gathered, or classed together"),
    Word::from( "growth",  "the process of increasing in physical size"),
    Word::from( "guard",  "watch over in order to protect or control"),
    Word::from( "guess",  "estimate or suppose (something) without sufficient information to be sure of being correct"),
    Word::from( "guest",  "a person who is invited to visit the home of or take part in a function organized by another"),
    Word::from( "guide",  "a person who advises or shows the way to others"),
    Word::from( "guilty",  "responsible for a specified wrongdoing"),
    Word::from( "habit",  "a settled or regular tendency or practice, especially one that is hard to give up"),
    Word::from( "handle",  "the part by which a thing is held, carried, or controlled"),
    Word::from( "happen",  "take place; occur"),
    Word::from( "happy",  "feeling or showing pleasure or contentment"),
    Word::from( "hardly",  "scarcely (used to qualify a statement by saying that it is true to an insignificant degree)"),
    Word::from( "health",  "the state of being free from illness or injury"),
    Word::from( "heart",  "a hollow muscular organ that pumps the blood through the circulatory system by rhythmic contraction and dilation"),
    Word::from( "heaven",  "a place regarded in various religions as the abode of God (or the gods) and the angels, and of the good after death, often traditionally depicted as being above the sky"),
    Word::from( "heavy",  "of great weight; difficult to lift or move"),
    Word::from( "height",  "the measurement from base to top or (of a standing person) from head to foot"),
    Word::from( "hello",  "used as a greeting or to begin a telephone conversation"),
    Word::from( "highly",  "to a high degree or level"),
    Word::from( "honest",  "free of deceit; truthful and sincere"),
    Word::from( "honey",  "a sweet, sticky yellowish-brown fluid made by bees and other insects from nectar collected from flowers"),
    Word::from( "honor",  "high respect; great esteem"),
    Word::from( "horror",  "an intense feeling of fear, shock, or disgust"),
    Word::from( "horse",  "a solid-hoofed plant-eating domesticated mammal with a flowing mane and tail, used for riding, racing, and to carry and pull loads"),
    Word::from( "hotel",  "an establishment providing accommodations, meals, and other services for travelers and tourists"),
    Word::from( "house",  "a building for human habitation, especially one that is lived in by a family or small group of people"),
    Word::from( "human",  "relating to or characteristic of people or human beings"),
    Word::from( "humor",  "the quality of being amusing or comic, especially as expressed in literature or speech"),
    Word::from( "hungry",  "feeling or displaying the need for food"),
    Word::from( "hunter",  "a person or animal that hunts"),
    Word::from( "ideal",  "satisfying one's conception of what is perfect; most suitable"),
    Word::from( "ignore",  "refuse to take notice of or acknowledge; disregard intentionally"),
    Word::from( "image",  "a representation of the external form of a person or thing in art"),
    Word::from( "impact",  "the action of one object coming forcibly into contact with another"),
    Word::from( "imply",  "strongly suggest the truth or existence of (something not expressly stated)"),
    Word::from( "impose",  "force (something unwelcome or unfamiliar) to be accepted or put in place"),
    Word::from( "income",  "money received, especially on a regular basis, for work or through investments"),
    Word::from( "indeed",  "used to emphasize a statement or response confirming something already suggested"),
    Word::from( "index",  "an alphabetical list of names, subjects, etc., with references to the places where they occur, typically found at the end of a book"),
    Word::from( "Indian",  "relating to India or to the subcontinent comprising India, Pakistan, and Bangladesh"),
    Word::from( "infant",  "a very young child or baby"),
    Word::from( "inform",  "give (someone) facts or information; tell"),
    Word::from( "injury",  "an instance of being injured"),
    Word::from( "inner",  "situated inside or further in; internal"),
    Word::from( "inside",  "the inner side or surface of something"),
    Word::from( "insist",  "demand something forcefully, not accepting refusal"),
    Word::from( "intend",  "have (a course of action) as one's purpose or objective; plan"),
    Word::from( "invest",  "expend money with the expectation of achieving a profit"),

  Word::from("invite",  "To request the presence or participation of someone."),
  Word::from("Iraqi",  "A person from Iraq or related to Iraq."),
  Word::from("Irish",  "A person from Ireland or related to Ireland."),
  Word::from("island",  "A piece of land surrounded by water."),
  Word::from("issue",  "An important topic or problem for discussion."),
  Word::from("itself",  "Used to refer to a thing or animal previously mentioned."),
  Word::from("jacket",  "A piece of outer clothing with sleeves, worn outdoors."),
  Word::from("Jewish",  "Relating to Jews or their culture or religion."),
  Word::from("joint",  "A point where two parts of something are connected."),
  Word::from("judge",  "A person who has the authority to decide cases in a court of law."),
  Word::from("juice",  "The liquid that comes from fruits or vegetables."),
  Word::from("junior",  "A person who is younger or of lower rank or status."),
  Word::from("killer",  "A person or thing that kills."),
  Word::from("knife",  "A tool with a blade for cutting."),
  Word::from("knock",  "To strike a surface noisily to attract attention."),
  Word::from("label",  "A piece of paper or material attached to an object to provide information about it."),
  Word::from("labor",  "Work, especially hard physical work."),
  Word::from("large",  "Of considerable size, extent, or capacity."),
  Word::from("later",  "At a time in the future or after the expected time."),
  Word::from("Latin",  "Relating to the language originally spoken in ancient Rome."),
  Word::from("latter",  "Referring to the second of two things mentioned."),
  Word::from("laugh",  "To make sounds and movements that express amusement."),
  Word::from("launch",  "To set in motion or start something, such as a project or a spacecraft."),
  Word::from("lawyer",  "A person who practices or studies law."),
  Word::from("layer",  "A sheet, quantity, or thickness of material that lies over or under another."),
  Word::from("leader",  "A person who leads or commands a group, organization, or country."),
  Word::from("league",  "A collection of people, countries, or groups that combine for mutual protection or cooperation."),
  Word::from("learn",  "To gain knowledge or skills through experience, study, or teaching."),
  Word::from("least",  "Smallest in size, amount, or degree."),
  Word::from("leave",  "To go away from or depart."),
  Word::from("legacy",  "Something handed down from an ancestor or from the past."),
  Word::from("legal",  "Relating to the law."),
  Word::from("legend",  "A traditional story sometimes popularly regarded as historical but not authenticated."),
  Word::from("lemon",  "A yellow citrus fruit with a sour taste."),
  Word::from("length",  "The measurement or extent of something from end to end."),
  Word::from("lesson",  "An amount of teaching given at one time; a period of learning or instruction."),
  Word::from("letter",  "A character representing one or more of the sounds used in speech; a written message."),
  Word::from("level",  "A specific height or line of achievement or progress."),
  Word::from("light",  "The natural agent that makes things visible; something that provides illumination."),
  Word::from("likely",  "Such as well might happen or be true; probable."),
  Word::from("limit",  "A point or level beyond which something does not or may not extend or pass."),
  Word::from("listen",  "To give one's attention to a sound."),
  Word::from("little",  "Small in size, amount, or degree."),
  Word::from("living",  "Alive; having life."),
  Word::from("local",  "Relating to a particular area or neighborhood."),
  Word::from("locate",  "To discover the exact place or position of."),
  Word::from("loose",  "Not firmly or tightly fixed in place."),
  Word::from("lovely",  "Exquisitely beautiful."),
  Word::from("lover",  "A person having a romantic relationship with someone."),
  Word::from("lower",  "Less high; situated below another part."),
  Word::from("lucky",  "Having, bringing, or resulting from good luck."),
  Word::from("lunch",  "A meal eaten in the middle of the day."),
  Word::from("mainly",  "For the most part; chiefly."),
  Word::from("major",  "Important, serious, or significant."),
  Word::from("maker",  "A person or thing that makes or produces something."),
  Word::from("makeup",  "Cosmetics used to enhance or alter the appearance."),
  Word::from("manage",  "To be in charge of; administer; run."),
  Word::from("manner",  "A way in which a thing is done or happens."),
  Word::from("margin",  "The edge or border of something."),
  Word::from("market",  "A place where goods are bought and sold."),
  Word::from("marry",  "To join in marriage."),
  Word::from("master",  "Having or showing very great skill or proficiency."),
  Word::from("match",  "A contest in which people or teams compete against each other."),
  Word::from("matter",  "A subject or situation under consideration."),
  Word::from("maybe",  "Perhaps; possibly."),
  Word::from("mayor",  "The elected head of a city, town, or other municipality."),
  Word::from("media",  "The main means of mass communication (broadcasting, publishing, and the Internet)."),
  Word::from("medium",  "An agency or means of doing something."),
  Word::from("member",  "A person, animal, or plant belonging to a particular group."),
  Word::from("memory",  "The faculty by which the mind stores and remembers information."),
  Word::from("mental",  "Relating to the mind."),
  Word::from("merely",  "Just; only."),
  Word::from("metal",  "A solid material that is typically hard, shiny, and malleable."),
  Word::from("meter",  "The fundamental unit of length in the metric system."),
  Word::from("method",  "A particular form of procedure for accomplishing or approaching something."),
  Word::from("middle",  "At an equal distance from the extremities of something; central."),
  Word::from("might",  "Possession of power, strength, or force."),
  Word::from("minor",  "Lesser in importance, seriousness, or significance."),
  Word::from("minute",  "A period of time equal to sixty seconds."),
  Word::from("mirror",  "A reflective surface, typically of glass coated with a metal amalgam."),
  Word::from("mm-hmm",  "A sound made in agreement, understanding, or acknowledgment."),
  Word::from("model",  "A three-dimensional representation of a person or thing or of a proposed structure."),
  Word::from("modern",  "Relating to the present or recent times as opposed to the remote past."),
  Word::from("modest",  "Unassuming or moderate in the estimation of one's abilities or achievements."),
  Word::from("moment",  "A very brief period of time."),
  Word::from("money",  "A current medium of exchange in the form of coins and banknotes."),
  Word::from("month",  "Each of the twelve named periods into which a year is divided."),
  Word::from("moral",  "Concerned with the principles of right and wrong behavior."),
  Word::from("mostly",  "As regards the greater part or number."),
  Word::from("mother",  "A woman in relation to her child or children."),
  Word::from("motion",  "The action or process of moving or being moved."),
  Word::from("motor",  "A machine, especially one powered by electricity or internal combustion."),
  Word::from("mount",  "To climb up or onto something."),
  Word::from("mouse",  "A small rodent that typically has a pointed snout."),
  Word::from("mouth",  "The opening in the lower part of the human face, surrounded by the lips."),
  Word::from("movie",  "A story or event recorded by a camera as a set of moving images."),
  Word::from("murder",  "The unlawful premeditated killing of one human being by another."),
  Word::from("muscle",  "A band or bundle of fibrous tissue that produces movement in the body."),
  Word::from("museum",  "A building in which objects of historical, scientific, artistic, or cultural interest are stored and exhibited."),
  Word::from("music",  "Vocal or instrumental sounds combined in such a way as to produce beauty of form, harmony, and expression of emotion."),
  Word::from("Muslim",  "A follower of the religion of Islam."),
  Word::from("mutual",  "Held in common by two or more parties."),
  Word::from("myself",  "Used by a speaker to refer to himself or herself as the object of a verb or preposition."),
  Word::from("naked",  "Without clothes."),
  Word::from("narrow",  "Of small width in relation to length."),
  Word::from("nation",  "A large aggregate of people united by common descent, history, culture, or language."),
  Word::from("native",  "A person born in a specified place or associated with a place by birth."),
  Word::from("nature",  "The phenomena of the physical world collectively, including plants, animals, the landscape, and other features and products of the earth."),
  Word::from("nearby",  "Close at hand; not far away."),
  Word::from("nearly",  "Almost; very close to."),
  Word::from("nerve",  "A bundle of fibers that transmits impulses of sensation to the brain or spinal cord."),
  Word::from("never",  "At no time in the past or future."),
  Word::from("newly",  "Recently."),
  Word::from("night",  "The period of darkness in each twenty-four hours; the time from sunset to sunrise."),
  Word::from("nobody",  "No person; no one."),
  Word::from("noise",  "A sound, especially one that is loud or unpleasant or that causes disturbance."),
  Word::from("normal",  "Conforming to a standard; usual, typical, or expected."),
  Word::from("north",  "The direction toward the top of a map, opposite to the south."),
  Word::from("notice",  "To become aware of."),
  Word::from("notion",  "A conception of or belief about something."),
  Word::from("novel",  "A fictitious prose narrative of book length, typically representing character and action with some degree of realism."),
  Word::from("number",  "A quantity or amount."),
  Word::from("nurse",  "A person trained to care for the sick or infirm, especially in a hospital."),
  Word::from("object",  "A material thing that can be seen and touched."),
  Word::from("obtain",  "To get, acquire, or secure something."),
  Word::from("occupy",  "To reside or have one's place of business in a building."),
  Word::from("occur",  "To happen; take place."),
  Word::from("ocean",  "A very large expanse of sea."),
  Word::from("offer",  "To present or proffer something for someone to accept or reject."),
  Word::from("office",  "A room, set of rooms, or building used as a place for commercial, professional, or bureaucratic work."),
  Word::from("often",  "Frequently; many times."),
  Word::from("onion",  "A swollen, edible bulb used as a vegetable, having a pungent taste and smell."),
  Word::from("online",  "Controlled by or connected to a computer."),
  Word::from("oppose",  "To disapprove of and attempt to prevent, especially by argument."),
  Word::from("option",  "A thing that is or may be chosen."),
  Word::from("orange",  "A round juicy citrus fruit with a tough bright reddish-yellow rind."),
  Word::from("order",  "The arrangement or disposition of people or things in relation to each other."),
  Word::from("origin",  "The point or place where something begins or is created."),
  Word::from("other",  "Used to refer to a person or thing that is different or distinct from one already mentioned or known."),
  Word::from("others",  "Other people or things."),
  Word::from("ought",  "Used to indicate duty or correctness, typically when criticizing someone’s actions."),
  Word::from("owner",  "A person who owns something."),
  Word::from("paint",  "A colored substance that is spread over a surface and dries to leave a thin decorative or protective coating."),
  Word::from("panel",  "A flat or curved component, typically rectangular, that forms or is set into the surface of a door, wall, or ceiling."),
  Word::from("paper",  "Material manufactured in thin sheets from the pulp of wood or other fibrous substances, used for writing, drawing, or printing on."),
  Word::from("parent",  "A person's father or mother."),
  Word::from("partly",  "To some extent; not completely."),
  Word::from("party",  "A social gathering of invited guests, typically involving eating, drinking, and entertainment."),
  Word::from("patch",  "A piece of cloth or other material used to mend or strengthen a torn or weak point."),
  Word::from("pause",  "A temporary stop in action or speech."),
  Word::from("peace",  "Freedom from disturbance; tranquility."),
  Word::from("people",  "Human beings in general or considered collectively."),
  Word::from("pepper",  "A pungent spice obtained from the berries of an East Indian climbing vine."),
  Word::from("period",  "A length or portion of time."),
  Word::from("permit",  "To give authorization or consent to (someone) to do something."),
  Word::from("person",  "A human being regarded as an individual."),
  Word::from("phase",  "A distinct period or stage in a process of change or forming part of something's development."),
  Word::from("phone",  "A telephone."),
  Word::from("photo",  "A photograph."),
  Word::from("phrase",  "A small group of words standing together as a conceptual unit, typically forming a component of a clause."),

  Word::from( "piano", "A large keyboard musical instrument with a wooden case enclosing a soundboard and metal strings, which are struck by hammers when the keys are depressed."),
  Word::from( "piece", "A portion of an object or of material, produced by cutting, tearing, or breaking the whole."),
  Word::from( "pilot", "A person who operates the flying controls of an aircraft."),
  Word::from( "pitch", "The quality of a sound governed by the rate of vibrations producing it; the degree of highness or lowness of a tone."),
  Word::from( "place", "A particular position or point in space."),
  Word::from( "plane", "A flat surface on which a straight line joining any two points on it would wholly lie; also refers to an aircraft."),
  Word::from( "planet", "A celestial body moving in an elliptical orbit around a star."),
  Word::from( "plant", "A living organism of the kind exemplified by trees, shrubs, herbs, grasses, ferns, and mosses, typically growing in a permanent site, absorbing water and inorganic substances through its roots, and synthesizing nutrients in its leaves by photosynthesis using the green pigment chlorophyll."),
  Word::from( "plate", "A flat dish, typically circular and made of china, from which food is eaten."),
  Word::from( "player", "A person taking part in a sport or game."),
  Word::from( "please", "To cause to feel happy and satisfied."),
  Word::from( "plenty", "A large or sufficient amount or quantity; more than enough."),
  Word::from( "pocket", "A small bag sewn into or on clothing so as to form part of it, used for carrying small articles."),
  Word::from( "poetry", "Literary work in which the expression of feelings and ideas is given intensity by the use of distinctive style and rhythm."),
  Word::from( "point", "A particular spot, place, or position in an area or on a map, object, or surface."),
  Word::from( "police", "The civil force of a state, responsible for the prevention and detection of crime and the maintenance of public order."),
  Word::from( "policy", "A course or principle of action adopted or proposed by an organization or individual."),
  Word::from( "porch", "A covered shelter projecting in front of the entrance of a building."),
  Word::from( "potato", "A starchy plant tuber which is one of the most important food crops, cooked and eaten as a vegetable."),
  Word::from( "pound", "A unit of weight in general use equal to 16 ounces avoirdupois (0.4536 kg)."),
  Word::from( "powder", "Fine, dry particles produced by the grinding, crushing, or disintegration of a solid substance."),
  Word::from( "power", "The ability or capacity to do something or act in a particular way."),
  Word::from( "prayer", "A solemn request for help or expression of thanks addressed to God or an object of worship."),
  Word::from( "prefer", "Like (one thing or person) better than another or others; tend to choose."),
  Word::from( "press", "To apply pressure to something to flatten, shape, or squeeze it."),
  Word::from( "pretty", "Attractive in a delicate way without being truly beautiful or handsome."),
  Word::from( "price", "The amount of money expected, required, or given in payment for something."),
  Word::from( "pride", "A feeling or deep pleasure or satisfaction derived from one's own achievements."),
  Word::from( "priest", "An ordained minister of the Catholic, Orthodox, or Anglican Church having the authority to perform certain rites and administer certain sacraments."),
  Word::from( "prime", "Of first importance; main."),
  Word::from( "print", "Produce (books, newspapers, magazines, etc.), especially in large quantities, by a mechanical process involving the transfer of text, images, or designs to paper."),
  Word::from( "prior", "Existing or coming before in time, order, or importance."),
  Word::from( "prison", "A building in which people are legally held as a punishment for a crime they have committed or while awaiting trial."),
  Word::from( "profit", "A financial gain, especially the difference between the amount earned and the amount spent in buying, operating, or producing something."),
  Word::from( "prompt", "Done without delay; immediate."),
  Word::from( "proof", "Evidence or argument establishing or helping to establish a fact or the truth of a statement."),
  Word::from( "proper", "Truly what something is said or regarded to be; genuine."),
  Word::from( "proud", "Feeling deep pleasure or satisfaction as a result of one's own achievements, qualities, or possessions."),
  Word::from( "prove", "Demonstrate the truth or existence of (something) by evidence or argument."),
  Word::from( "public", "Of or concerning the people as a whole."),
  Word::from( "pursue", "Follow (someone or something) in order to catch or attack them."),
  Word::from( "quick", "Moving fast or doing something in a short time."),
  Word::from( "quiet", "Making little or no noise."),
  Word::from( "quite", "To the utmost or most absolute extent or degree; absolutely; completely."),
  Word::from( "quote", "Repeat or copy out (a group of words from a text or speech), typically with an indication that one is not the original author or speaker."),
  Word::from( "racial", "Relating to race."),
  Word::from( "radio", "The transmission and reception of electromagnetic waves of radio frequency, especially those carrying sound messages."),
  Word::from( "raise", "Lift or move to a higher position or level."),
  Word::from( "range", "The area of variation between upper and lower limits on a particular scale."),
  Word::from( "rapid", "Happening in a short time or at a fast pace."),
  Word::from( "rarely", "Not often; seldom."),
  Word::from( "rather", "Used to indicate one's preference in a particular matter."),
  Word::from( "rating", "A classification or ranking of someone or something based on a comparative assessment of their quality, standard, or performance."),
  Word::from( "ratio", "The quantitative relation between two amounts showing the number of times one value contains or is contained within the other."),
  Word::from( "reach", "Stretch out an arm in a specified direction in order to touch or grasp something."),
  Word::from( "react", "Respond or behave in a particular way in response to something."),
  Word::from( "reader", "A person who reads or who is fond of reading."),
  Word::from( "ready", "In a suitable state for an activity, action, or situation; fully prepared."),
  Word::from( "really", "In actual fact, as opposed to what is said or imagined to be true or possible."),
  Word::from( "reason", "A cause, explanation, or justification for an action or event."),
  Word::from( "recall", "Bring (a fact, event, or situation) back into one's mind; remember."),
  Word::from( "recent", "Having happened, begun, or been done not long ago; belonging to a past period comparatively close to the present."),
  Word::from( "recipe", "A set of instructions for preparing a particular dish, including a list of the ingredients required."),
  Word::from( "record", "A thing constituting a piece of evidence about the past, especially an account kept in writing or some other permanent form."),
  Word::from( "reduce", "Make smaller or less in amount, degree, or size."),
  Word::from( "refer", "Mention or allude to."),
  Word::from( "reform", "Make changes in (something, typically a social, political, or economic institution or practice) in order to improve it."),
  Word::from( "refuse", "Indicate or show that one is not willing to do something."),
  Word::from( "regard", "Consider or think of (someone or something) in a specified way."),
  Word::from( "regime", "A government, especially an authoritarian one."),
  Word::from( "region", "An area, especially part of a country or the world having definable characteristics but not always fixed boundaries."),
  Word::from( "reject", "Dismiss as inadequate, unacceptable, or faulty."),
  Word::from( "relate", "Make or show a connection between."),
  Word::from( "relax", "Make or become less tense or anxious."),
  Word::from( "relief", "A feeling of reassurance and relaxation following release from anxiety or distress."),
  Word::from( "remain", "Continue to exist, especially after other similar or related people or things have ceased to do so."),
  Word::from( "remind", "Cause (someone) to remember someone or something."),
  Word::from( "remote", "Situated far from the main centers of population; distant."),
  Word::from( "remove", "Take (something) away or off from the position occupied."),
  Word::from( "repeat", "Say again something one has already said."),
  Word::from( "reply", "Say something in response to something someone has said."),
  Word::from( "report", "Give a spoken or written account of something that one has observed, heard, done, or investigated."),
  Word::from( "resist", "Withstand the action or effect of."),
  Word::from( "resort", "A place that is a popular destination for vacations or recreation, or which is frequented for a particular purpose."),
  Word::from( "result", "A consequence, effect, or outcome of something."),
  Word::from( "retain", "Continue to have (something); keep possession of."),
  Word::from( "retire", "Leave one's job and cease to work, typically upon reaching the normal age for leaving employment."),
  Word::from( "return", "Come or go back to a place or person."),
  Word::from( "reveal", "Make (previously unknown or secret information) known to others."),
  Word::from( "review", "A formal assessment or examination of something with the possibility or intention of instituting change if necessary."),
  Word::from( "rhythm", "A strong, regular, repeated pattern of movement or sound."),
  Word::from( "rifle", "A gun, especially one fired from shoulder level, having a long spirally grooved barrel intended to make a bullet spin and thereby have greater accuracy over a long distance."),
  Word::from( "right", "Morally good, justified, or acceptable."),
  Word::from( "river", "A large natural stream of water flowing in a channel to the sea, a lake, or another river."),
  Word::from( "rough", "Having an uneven or irregular surface; not smooth or level."),
  Word::from( "round", "Shaped like or approximately like a circle or cylinder."),
  Word::from( "route", "A way or course taken in getting from a starting point to a destination."),
  Word::from( "rural", "In, relating to, or characteristic of the countryside rather than the town."),
  Word::from( "sacred", "Connected with God or a god or dedicated to a religious purpose and so deserving veneration."),
  Word::from( "safety", "The condition of being protected from or unlikely to cause danger, risk, or injury."),
  Word::from( "salad", "A cold dish of various mixtures of raw or cooked vegetables, usually seasoned with oil, vinegar, or other dressing and sometimes accompanied by meat, fish, or other ingredients."),
  Word::from( "salary", "A fixed regular payment, typically paid on a monthly or biweekly basis but often expressed as an annual sum, made by an employer to an employee, especially a professional or white-collar worker."),
  Word::from( "sales", "The exchange of a commodity for money; the action of selling something."),
  Word::from( "sample", "A small part or quantity intended to show what the whole is like."),
  Word::from( "sauce", "A liquid or semi-liquid substance served with food to add moistness and flavor."),
  Word::from( "saving", "An economy of or reduction in money, time, or another resource."),
  Word::from( "scale", "A system or series of marks used for measuring or registering."),
  Word::from( "scared", "Fearful; frightened."),
  Word::from( "scene", "The place where an incident in real life or fiction occurs or occurred."),
  Word::from( "scheme", "A large-scale systematic plan or arrangement for attaining some particular object or putting a particular idea into effect."),
  Word::from( "school", "An institution for educating children."),
  Word::from( "scope", "The extent of the area or subject matter that something deals with or to which it is relevant."),
  Word::from( "score", "The number of points, goals, runs, etc., achieved in a game or by a team or an individual."),
  Word::from( "scream", "Give a long, loud, piercing cry or cries expressing excitement, great emotion, or pain."),
  Word::from( "screen", "A flat panel or area on an electronic device such as a television, computer, or smartphone, on which images and data are displayed."),
  Word::from( "script", "Handwriting as distinct from print; written characters."),
  Word::from( "search", "Try to find something by looking or otherwise seeking carefully and thoroughly."),
  Word::from( "season", "Each of the four divisions of the year (spring, summer, autumn, and winter) marked by particular weather patterns and daylight hours, resulting from the earth's changing position with regard to the sun."),
  Word::from( "secret", "Not known or seen or not meant to be known or seen by others."),
  Word::from( "sector", "An area or portion that is distinct from others."),
  Word::from( "secure", "Fixed or fastened so as not to give way, become loose, or be lost."),
  Word::from( "seize", "Take hold of suddenly and forcibly."),
  Word::from( "select", "Carefully choose as being the best or most suitable."),
  Word::from( "Senate", "Any of various legislative or governing bodies, in particular."),
  Word::from( "senior", "Of or for older or more experienced people."),
  Word::from( "sense", "A faculty by which the body perceives an external stimulus; one of the faculties of sight, smell, hearing, taste, and touch."),
  Word::from( "series", "A number of things, events, or people of a similar kind or related nature coming one after another."),
  Word::from( "serve", "Perform duties or services for (another person or an organization)."),
  Word::from( "settle", "Resolve or reach an agreement about (an argument or problem)."),
  Word::from( "seven", "Equivalent to the sum of three and four; one more than six, or three less than ten; 7."),
  Word::from( "severe", "Of something bad or undesirable: very great; intense."),
  Word::from( "sexual", "Relating to the instincts, physiological processes, and activities connected with physical attraction or intimate physical contact between individuals."),
  Word::from( "shade", "Comparative darkness and coolness caused by shelter from direct sunlight."),
  Word::from( "shadow", "A dark area or shape produced by a body coming between rays of light and a surface."),
  Word::from( "shake", "Move (an object) up and down or from side to side with rapid, forceful, jerky movements."),
  Word::from( "shall", "Expressing the future tense."),
  Word::from( "shape", "The external form, contours, or outline of someone or something."),
  Word::from( "share", "A part or portion of a larger amount that is divided among a number of people, or to which a number of people contribute."),
  Word::from( "sharp", "Having an edge or point that is able to cut or pierce something."),
  Word::from( "sheet", "A large rectangular piece of cotton or other fabric used on a bed to cover the mattress and as a layer underneath blankets."),
  Word::from( "shelf", "A flat, horizontal surface, typically one of several, attached to a wall or forming part of a piece of furniture."),
  Word::from( "shell", "The hard protective outer case of a mollusk or crustacean."),
  Word::from( "shift", "Move or cause to move from one place to another, especially over a small distance."),
  Word::from( "shine", "Give out a bright light; glow with reflected light."),
  Word::from( "shirt", "A garment for the upper body made of cotton or a similar fabric, with a collar and sleeves, and with buttons down the front."),
  Word::from( "shock", "A sudden upsetting or surprising event or experience."),
  Word::from( "shoot", "Kill or wound (a person or animal) with a bullet or arrow."),
  Word::from( "shore", "The land along the edge of a sea, lake, or other large body of water."),
  Word::from( "short", "Measuring a small distance from end to end."),
  Word::from( "should", "Used to indicate obligation, duty, or correctness, typically when criticizing someone's actions."),
  Word::from( "shout", "Utter a loud call or cry, typically as an expression of a strong emotion."),
  Word::from( "shower", "A brief and usually light fall of rain, hail, sleet, or snow."),
  Word::from( "shrug", "Raise (one's shoulders) slightly and momentarily to express doubt, ignorance, or indifference."),
  Word::from( "sight", "The faculty or power of seeing."),
  Word::from( "signal", "A gesture, action, or sound that is used to convey information or instructions, typically by prearrangement between the parties concerned."),
  Word::from( "silent", "Not making or accompanied by any sound."),
  Word::from( "silver", "A precious shiny grayish-white metal, the chemical element of atomic number 47."),
  Word::from( "simple", "Easily understood or done; presenting no difficulty."),
  Word::from( "simply", "In a straightforward or plain manner."),
  Word::from( "since", "In the intervening period between (the time mentioned) and the time under consideration, typically the present."),
  Word::from( "singer", "A person who sings, especially professionally."),
  Word::from( "single", "Only one; not one of several."),
  Word::from( "sister", "A woman or girl in relation to other daughters and sons of her parents."),
  Word::from( "skill", "The ability to do something well; expertise."),
  Word::from( "slave", "A person who is the legal property of another and is forced to obey them."),
  Word::from( "sleep", "A condition of body and mind which typically recurs for several hours every night, in which the nervous system is relatively inactive, the eyes closed, the postural muscles relaxed, and consciousness practically suspended."),
  Word::from( "slice", "A thin, broad piece of food, such as bread, meat, or cake, cut from a larger portion."),
  Word::from( "slide", "Move along a smooth surface while maintaining continuous contact with it."),
  Word::from( "slight", "Small in degree; inconsiderable."),
  Word::from( "slowly", "At a slow speed; not quickly."),
  Word::from( "small", "Of a size that is less than normal or usual."),
  Word::from( "smart", "Having or showing a quick-witted intelligence."),
  Word::from( "smell", "Perceive or detect the odor or scent of (something)."),
  Word::from( "smile", "Form one's features into a pleased, kind, or amused expression, typically with the corners of the mouth turned up and the front teeth exposed."),
  Word::from( "smoke", "A visible suspension of carbon or other particles in air, typically one emitted from a burning substance."),
  Word::from( "smooth", "Having an even and regular surface or consistency; free from perceptible projections, lumps, or indentations."),
  Word::from( "soccer", "A game played by two teams of eleven players with a round ball that may not be touched with the hands or arms during play, except by the goalkeepers. The object of the game is to score goals by kicking or heading the ball into the opponents' goal."),
  Word::from( "social", "Relating to society or its organization."),
  Word::from( "solar", "Relating to or determined by the sun."),
  Word::from( "solid", "Firm and stable in shape; not liquid or fluid."),
  Word::from( "solve", "Find an answer to, explanation for, or means of effectively dealing with (a problem or mystery)."),
  Word::from( "sorry", "Feeling distress, especially through sympathy with someone else's misfortune."),

  Word::from( "sound", "Vibrations that travel through the air and can be heard by humans or animals."),
  Word::from( "source", "A place, person, or thing from which something originates or can be obtained."),
  Word::from( "south", "The direction towards the bottom of a map; opposite of north."),
  Word::from( "Soviet", "Relating to the former Soviet Union or its people."),
  Word::from( "space", "The vast, seemingly infinite expanse in which all celestial bodies exist."),
  Word::from( "speak", "To utter words or articulate sounds with the ordinary voice."),
  Word::from( "speech", "The expression of or the ability to express thoughts and feelings by articulate sounds."),
  Word::from( "speed", "The rate at which someone or something moves or operates."),
  Word::from( "spend", "To use money to buy goods or services or to use time in a particular manner."),
  Word::from( "spirit", "The non-physical part of a person regarded as their true self."),
  Word::from( "split", "To divide or break something into parts or sections."),
  Word::from( "sport", "An activity involving physical exertion and skill, often competitive in nature."),
  Word::from( "spread", "To open out something so as to extend its surface area, width, or length."),
  Word::from( "spring", "The season between winter and summer when plants begin to grow."),
  Word::from( "square", "A plane figure with four equal straight sides and four right angles."),
  Word::from( "stable", "Not likely to change or fail; firmly established."),
  Word::from( "staff", "The group of people who work for an organization or business."),
  Word::from( "stage", "A raised platform where performances or public events are presented."),
  Word::from( "stair", "A set of steps leading from one floor of a building to another."),
  Word::from( "stake", "A strong wooden or metal post driven into the ground to support something."),
  Word::from( "stand", "To be in an upright position on the feet."),
  Word::from( "stare", "To look fixedly or vacantly at someone or something."),
  Word::from( "start", "To begin or initiate something."),
  Word::from( "state", "A nation or territory considered as an organized political community under one government."),
  Word::from( "status", "The relative social, professional, or other standing of someone or something."),
  Word::from( "steady", "Firmly fixed, supported, or balanced; not shaking or moving."),
  Word::from( "steal", "To take another person's property without permission or legal right."),
  Word::from( "steel", "A strong, hard metal made of iron and carbon, used in construction and manufacturing."),
  Word::from( "stick", "A thin piece of wood or other material, typically used to support or prop up something."),
  Word::from( "still", "Not moving or making a sound; deep silence and calm."),
  Word::from( "stock", "The goods or merchandise kept on the premises of a business and available for sale or distribution."),
  Word::from( "stone", "A hard, solid nonmetallic mineral matter of which rock is made."),
  Word::from( "store", "A retail establishment selling items to the public."),
  Word::from( "storm", "A violent disturbance of the atmosphere with strong winds and usually rain, thunder, lightning, or snow."),
  Word::from( "story", "An account of imaginary or real people and events told for entertainment."),
  Word::from( "stream", "A small, narrow river."),
  Word::from( "street", "A public road in a city or town, typically with houses and buildings on one or both sides."),
  Word::from( "stress", "A state of mental or emotional strain or tension resulting from adverse or demanding circumstances."),
  Word::from( "strike", "To hit forcibly and deliberately with one's hand or a weapon or other implement."),
  Word::from( "string", "A thin piece of cord used to tie, bind, or hang other objects."),
  Word::from( "strip", "A long, narrow piece of cloth, paper, or other material."),
  Word::from( "stroke", "An act of hitting or striking someone or something; a movement of a pen, brush, or hand."),
  Word::from( "strong", "Having the power to move heavy weights or perform other physically demanding tasks."),
  Word::from( "studio", "A room where an artist, photographer, sculptor, etc., works."),
  Word::from( "study", "The devotion of time and attention to gaining knowledge of an academic subject, especially by means of books."),
  Word::from( "stuff", "Matter, material, articles, or activities of a specified or indeterminate kind that are being referred to, indicated, or implied."),
  Word::from( "stupid", "Lacking intelligence or common sense."),
  Word::from( "style", "A manner of doing something, especially one characteristic of a particular period, place, person, or movement."),
  Word::from( "submit", "To present or propose something for review, consideration, or decision."),
  Word::from( "sudden", "Occurring or done quickly and unexpectedly or without warning."),
  Word::from( "suffer", "To experience or be subjected to something bad or unpleasant."),
  Word::from( "sugar", "A sweet crystalline substance obtained from various plants, especially sugar cane and sugar beet, used as a sweetener in food and drink."),
  Word::from( "summer", "The warmest season of the year, in the northern hemisphere from June to August and in the southern hemisphere from December to February."),
  Word::from( "summit", "The highest point of a hill or mountain; a meeting between heads of government."),
  Word::from( "super", "Excellent; very good."),
  Word::from( "supply", "Make (something needed or wanted) available to someone; provide."),
  Word::from( "surely", "With assurance or confidence; certainly."),
  Word::from( "survey", "To examine and record the area and features of (an area of land) so as to construct a map, plan, or description."),
  Word::from( "swear", "To make a solemn statement or promise undertaking to do something or affirming that something is the case."),
  Word::from( "sweep", "To clean an area by brushing away dirt or litter."),
  Word::from( "sweet", "Having the pleasant taste characteristic of sugar or honey; not salty, sour, or bitter."),
  Word::from( "swing", "To move back and forth or from side to side while suspended or on an axis."),
  Word::from( "switch", "To change the position, direction, or focus of."),
  Word::from( "symbol", "A thing that represents or stands for something else, especially a material object representing something abstract."),
  Word::from( "system", "A set of connected things or parts forming a complex whole, in particular."),
  Word::from( "table", "A piece of furniture with a flat top and one or more legs, providing a level surface for eating, writing, or working."),
  Word::from( "tactic", "An action or strategy carefully planned to achieve a specific end."),
  Word::from( "talent", "Natural aptitude or skill."),
  Word::from( "target", "A person, object, or place selected as the aim of an attack."),
  Word::from( "taste", "The sensation of flavor perceived in the mouth and throat on contact with a substance."),
  Word::from( "teach", "To impart knowledge or skill; give instruction to."),
  Word::from( "tennis", "A game in which two or four players strike a ball with rackets over a net stretched across a court."),
  Word::from( "terms", "Words or expressions used in relation to a particular subject."),
  Word::from( "terror", "Extreme fear."),
  Word::from( "thank", "To express gratitude to (someone), especially by saying 'Thank you'."),
  Word::from( "thanks", "An expression of gratitude."),
  Word::from( "their", "Belonging to or associated with the people or things previously mentioned or easily identified."),
  Word::from( "theme", "The subject of a talk, piece of writing, exhibition, etc.; a topic."),
  Word::from( "theory", "A supposition or a system of ideas intended to explain something, especially one based on general principles independent of the thing to be explained."),
  Word::from( "there", "In, at, or to that place or position."),
  Word::from( "these", "Used to identify a specific group of items previously mentioned or easily identified."),
  Word::from( "thick", "With opposite sides or surfaces that are a great or relatively great distance apart."),
  Word::from( "thing", "An object that one need not, cannot, or does not wish to give a specific name to."),
  Word::from( "think", "To have a particular opinion, belief, or idea about someone or something."),
  Word::from( "third", "Constituting number three in a sequence; 3rd."),
  Word::from( "thirty", "The number equivalent to the product of three and ten; 30."),
  Word::from( "those", "Used to identify a specific group of items previously mentioned or easily identified."),
  Word::from( "though", "Despite the fact that; although."),
  Word::from( "threat", "A statement of an intention to inflict pain, injury, damage, or other hostile action on someone in retribution for something done or not done."),
  Word::from( "three", "The number equivalent to the sum of one and two; 3."),
  Word::from( "throat", "The passage which leads from the back of the mouth of a person or animal."),
  Word::from( "throw", "To propel (something) with force through the air by a movement of the arm and hand."),
  Word::from( "ticket", "A piece of paper or card that gives the holder a certain right, especially to enter a place, travel by public transport, or participate in an event."),
  Word::from( "tight", "Fixed, fastened, or closed firmly; hard to move, undo, or open."),
  Word::from( "tired", "In need of sleep or rest; weary."),
  Word::from( "tissue", "Any of the distinct types of material of which animals or plants are made, consisting of specialized cells and their products."),
  Word::from( "title", "The name of a book, composition, or other artistic work."),
  Word::from( "today", "On or in the course of this present day."),
  Word::from( "tomato", "A glossy red, or occasionally yellow, pulpy edible fruit that is typically eaten as a vegetable or in salad."),
  Word::from( "tongue", "The fleshy muscular organ in the mouth used for tasting, licking, swallowing, and (in humans) articulating speech."),
  Word::from( "tooth", "Each of a set of hard, bony enamel-coated structures in the jaws of most vertebrates, used for biting and chewing."),
  Word::from( "topic", "A matter dealt with in a text, discourse, or conversation; a subject."),
  Word::from( "total", "Comprising the whole number or amount."),
  Word::from( "touch", "To come into or be in contact with."),
  Word::from( "tough", "Strong enough to withstand adverse conditions or rough handling."),
  Word::from( "toward", "In the direction of."),
  Word::from( "tower", "A tall, narrow building, either freestanding or forming part of a building such as a church or castle."),
  Word::from( "trace", "To find or discover by investigation."),
  Word::from( "track", "A rough path or minor road, typically one beaten by use rather than constructed."),
  Word::from( "trade", "The action of buying and selling goods and services."),
  Word::from( "trail", "A mark or a series of signs or objects left behind by the passage of someone or something."),
  Word::from( "train", "A series of connected railroad cars pulled or pushed by one or more locomotives."),
  Word::from( "travel", "To make a journey, typically of some length or abroad."),
  Word::from( "treat", "To behave towards or deal with in a certain way."),
  Word::from( "treaty", "A formally concluded and ratified agreement between countries."),
  Word::from( "trend", "A general direction in which something is developing or changing."),
  Word::from( "trial", "A formal examination of evidence by a judge, typically in order to decide guilt in a case of criminal or civil proceedings."),
  Word::from( "tribe", "A social division in a traditional society consisting of families or communities linked by social, economic, religious, or blood ties."),
  Word::from( "trick", "A cunning act or scheme intended to deceive or outwit someone."),
  Word::from( "troop", "A group of soldiers, especially a cavalry unit commanded by a captain."),
  Word::from( "truck", "A large, heavy motor vehicle for transporting goods or troops."),
  Word::from( "truly", "In a truthful way."),
  Word::from( "trust", "Firm belief in the reliability, truth, ability, or strength of someone or something."),
  Word::from( "truth", "The quality or state of being true."),
  Word::from( "tunnel", "An artificial underground passage, especially one built through a hill or under a building, road, or river."),
  Word::from( "twelve", "The number equivalent to the sum of ten and two; 12."),
  Word::from( "twenty", "The number equivalent to the product of two and ten; 20."),
  Word::from( "twice", "Two times; on two occasions."),
  Word::from( "unable", "Lacking the skill, means, or opportunity to do something."),
  Word::from( "uncle", "The brother of one's father or mother or the husband of one's aunt."),
  Word::from( "under", "Extending or directly below."),
  Word::from( "union", "The action or fact of joining or being joined, especially in a political context."),
  Word::from( "unique", "Being the only one of its kind; unlike anything else."),
  Word::from( "United", "Joined together politically, for a common purpose, or by common feelings."),
  Word::from( "unless", "Except if."),
  Word::from( "unlike", "Different from; not similar to."),
  Word::from( "until", "Up to the point in time or the event mentioned."),
  Word::from( "upper", "Situated above another part."),
  Word::from( "urban", "In, relating to, or characteristic of a city or town."),
  Word::from( "useful", "Able to be used for a practical purpose or in several ways."),
  Word::from( "usual", "Habitually or typically occurring or done; customary."),
  Word::from( "valley", "A low area of land between hills or mountains, typically with a river or stream flowing through it."),
  Word::from( "value", "The regard that something is held to deserve; the importance, worth, or usefulness of something."),
  Word::from( "versus", "Against (especially in sports and legal use)."),
  Word::from( "vessel", "A ship or large boat."),
  Word::from( "victim", "A person harmed, injured, or killed as a result of a crime, accident, or other event or action."),
  Word::from( "video", "The recording, reproducing, or broadcasting of moving visual images."),
  Word::from( "viewer", "A person who looks at or inspects something."),
  Word::from( "virtue", "Behavior showing high moral standards."),
  Word::from( "virus", "A microorganism that is smaller than a bacterium that cannot grow or reproduce apart from a living cell."),
  Word::from( "vision", "The faculty or state of being able to see."),
  Word::from( "visit", "To go to see and spend time with (someone) socially."),
  Word::from( "visual", "Relating to seeing or sight."),
  Word::from( "vital", "Absolutely necessary or important; essential."),
  Word::from( "voice", "The sound produced in a person's larynx and uttered through the mouth, as speech or song."),
  Word::from( "volume", "A book forming part of a work or series."),
  Word::from( "voter", "A person who has a right to vote, especially in an election."),
  Word::from( "wander", "To walk or move in a leisurely, casual, or aimless way."),
  Word::from( "waste", "Use or expend carelessly, extravagantly, or to no purpose."),
  Word::from( "watch", "To look at or observe attentively over a period of time."),
  Word::from( "water", "A clear, colorless, odorless, and tasteless liquid that forms the seas, lakes, rivers, and rain."),
  Word::from( "wealth", "An abundance of valuable possessions or money."),
  Word::from( "weapon", "A thing designed or used for inflicting bodily harm or physical damage."),
  Word::from( "weekly", "Happening once a week or every week."),
  Word::from( "weigh", "To find out how heavy (someone or something) is, typically using scales."),
  Word::from( "weight", "A body's relative mass or the quantity of matter contained by it, giving rise to a downward force; the heaviness of a person or thing."),
  Word::from( "wheel", "A circular object that revolves on an axle and forms part of a machine."),
  Word::from( "where", "In or to what place or position."),
  Word::from( "which", "Asking for information specifying one or more people or things from a definite set."),
  Word::from( "while", "A period of time."),
  Word::from( "white", "The color of milk or fresh snow, due to the reflection of most wavelengths of visible light; the opposite of black."),
  Word::from( "whole", "All of; entire."),
  Word::from( "whose", "Belonging to or associated with which person."),
  Word::from( "widely", "Over a wide area or range; extensively."),
  Word::from( "window", "An opening in the wall or roof of a building or vehicle that is fitted with glass or other transparent material in a frame to admit light or air and allow people to see out."),
  Word::from( "winner", "A person or thing that wins something."),
  Word::from( "winter", "The coldest season of the year, in the northern hemisphere from December to February and in the southern hemisphere from June to August."),
  Word::from( "wisdom", "The quality of having experience, knowledge, and good judgment; the quality of being wise."),
  Word::from( "within", "Inside (something)."),
  Word::from( "woman", "An adult human female."),
  Word::from( "wonder", "A feeling of amazement and admiration, caused by something beautiful, remarkable, or unfamiliar."),
  Word::from( "wooden", "Made of wood."),
  Word::from( "worker", "A person who does a specified type of work or who works in a specified way."),
  Word::from( "works", "Activity involving mental or physical effort done in order to achieve a purpose or result."),
  Word::from( "world", "The earth, together with all of its countries, peoples, and natural features."),
  Word::from( "worry", "To give way to anxiety or unease; allow one's mind to dwell on difficulty or troubles."),
  Word::from( "worth", "Equivalent in value to the sum or item specified."),
  Word::from( "would", "Past of will, expressing the conditional mood."),
  Word::from( "wound", "An injury to living tissue caused by a cut, blow, or other impact."),
  Word::from( "write", "To mark (letters, words, or other symbols) on a surface, typically paper, with a pen, pencil, or similar implement."),
  Word::from( "writer", "A person who has written a particular text."),
  Word::from( "wrong", "Not correct or true; incorrect."),
  Word::from( "yellow", "Of the color between green and orange in the spectrum, a primary subtractive color complementary to blue."),
  Word::from( "yield", "To produce or provide (a natural, agricultural, or industrial product)."),
  Word::from( "young", "Having lived or existed for only a short time."),
  Word::from( "yours", "Belonging to or associated with the person or people that the speaker is addressing."),
  Word::from( "youth", "The period between childhood and adult age."),
]
    }
}
